// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['inject', 'p2', 'movement/rotate', 'movement/directions', 'movement/force', 'movement/steer', 'movement/velocity', 'movement/separate', 'movement/cohere', 'movement/align', 'movement/lineup', 'movement/squaregroup'], function(inject, p2) {
  var Physics;
  Physics = (function() {
    function Physics() {
      this.eachbydistance = __bind(this.eachbydistance, this);
      this.person = __bind(this.person, this);
      this.register = __bind(this.register, this);
      this.step = __bind(this.step, this);
      this.entities = [];
      this.world = new p2.World({
        gravity: [0, 0]
      });
      this.maxvelocity = inject.one('max velocity');
      this.offsetwidth = 5;
      inject.bind('step', this.step);
      inject.bind('register physics', this.register);
      inject.bind('each by distance', this.eachbydistance);
    }

    Physics.prototype.step = function() {
      var entity, length, _i, _len, _ref, _results;
      this.world.step(1 / 60);
      _ref = this.entities;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        entity = _ref[_i];
        length = p2.vec2.len(entity.b.velocity);
        if (length > this.maxvelocity) {
          p2.vec2.normalize(entity.b.velocity, entity.b.velocity);
          p2.vec2.scale(entity.b.velocity, entity.b.velocity, this.maxvelocity);
        }
        if (entity.b.position[0] < -this.offsetwidth) {
          entity.b.position[0] = width + this.offsetwidth;
        }
        if (entity.b.position[0] > width + this.offsetwidth) {
          entity.b.position[0] = -this.offsetwidth;
        }
        if (entity.b.position[1] < -this.offsetwidth) {
          entity.b.position[1] = height + this.offsetwidth;
        }
        if (entity.b.position[1] > height + this.offsetwidth) {
          _results.push(entity.b.position[1] = -this.offsetwidth);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Physics.prototype.register = function(entity, n, p, v) {
      if (this[n] != null) {
        return this[n](entity, p, v);
      }
    };

    Physics.prototype.person = function(entity, p, v) {
      var body, shape;
      body = new p2.Body({
        mass: 1,
        position: p,
        velocity: v
      });
      body.damping = 0;
      shape = new p2.Circle(6);
      body.addShape(shape);
      this.world.addBody(body);
      return this.entities.push(entity.phys = {
        b: body,
        s: shape,
        e: function() {
          return entity;
        }
      });
    };

    Physics.prototype.eachbydistance = function(p, r, cb) {
      var distance, entity, _i, _len, _ref, _results;
      _ref = this.entities;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        entity = _ref[_i];
        distance = p2.vec2.dist(p, entity.b.position);
        if (distance > r) {
          continue;
        }
        _results.push(cb(distance, entity.e()));
      }
      return _results;
    };

    return Physics;

  })();
  return new Physics();
});
