// Generated by CoffeeScript 1.7.1
define(['inject', 'p2'], function(inject, p2) {
  return inject.bind('align', function(entity, scale) {
    var averagedirection, count, force;
    averagedirection = [0, 0];
    count = 0;
    inject.one('each by distance')(entity.phys.b.position, 50, function(d, e) {
      if (e === entity || (e.ai == null)) {
        return;
      }
      p2.vec2.add(averagedirection, averagedirection, e.phys.b.velocity);
      return count++;
    });
    if (p2.vec2.len(averagedirection) === 0) {
      return;
    }
    inject.one('scale to max velocity')(averagedirection);
    force = inject.one('calculate steering')(entity.phys.b.velocity, averagedirection);
    p2.vec2.scale(force, force, scale);
    return inject.one('apply force')(entity, force);
  });
});
