// Generated by CoffeeScript 1.7.1
define(['inject', 'p2'], function(inject, p2) {
  return inject.bind('cohere', function(entity, scale) {
    var averageposition, count, force, iscommunity, targetvelocity;
    averageposition = [0, 0];
    count = 0;
    inject.one('each by distance')(entity.phys.b.position, 100, function(d, e) {
      if (e === entity || (e.ai == null)) {
        return;
      }
      p2.vec2.add(averageposition, averageposition, e.phys.b.position);
      return count++;
    });
    inject.one('abs stat')(entity, {
      iscommunity: count > 0
    });
    iscommunity = count > 0;
    if (p2.vec2.len(averageposition) === 0) {
      return;
    }
    p2.vec2.scale(averageposition, averageposition, 1 / count);
    targetvelocity = inject.one('calculate seeking')(entity.phys.b.position, averageposition);
    force = inject.one('calculate steering')(entity.phys.b.velocity, targetvelocity);
    p2.vec2.scale(force, force, scale);
    return inject.one('apply force')(entity, force);
  });
});
