// Generated by CoffeeScript 1.7.1
define(['inject', 'p2'], function(inject, p2) {
  return inject.bind('calculate perpendicular', (function(_this) {
    return function(from, to, point) {
      var calc, lambda, unit;
      unit = [0, 0];
      p2.vec2.sub(unit, to, from);
      p2.vec2.normalize(unit, unit);
      calc = [0, 0];
      p2.vec2.sub(calc, point, from);
      lambda = p2.vec2.dot(unit, calc);
      p2.vec2.scale(calc, unit, lambda);
      p2.vec2.add(calc, from, calc);
      return calc;
    };
  })(this));
});
