// Generated by CoffeeScript 1.7.1
define(['inject', 'p2'], function(inject, p2) {
  return inject.bind('apply force', (function(_this) {
    return function(entity, f) {
      return p2.vec2.add(entity.phys.b.force, entity.phys.b.force, f);
    };
  })(this));
});
