// Generated by CoffeeScript 1.7.1
define(['inject', 'p2'], function(inject, p2) {
  return inject.bind('line up', function(entity, scale) {
    var distances, force, mag;
    entity.target = null;
    distances = [];
    inject.one('each by distance')(entity.phys.b.position, 50, (function(_this) {
      return function(d, e) {
        if (e === entity || (e.ai == null)) {
          return;
        }
        return distances.push({
          d: d,
          e: e
        });
      };
    })(this));
    if (distances.length === 0) {
      return;
    }
    distances.sort((function(_this) {
      return function(a, b) {
        return a.d - b.d;
      };
    })(this));
    if (distances.length === 1) {
      entity.target = p2.vec2.clone(distances[0].e.phys.b.position);
    } else {
      entity.target = inject.one('calculate perpendicular')(distances[0].e.phys.b.position, distances[1].e.phys.b.position, entity.phys.b.position);
    }
    mag = [0, 0];
    p2.vec2.sub(mag, entity.target, entity.phys.b.position);
    inject.one('scale to max velocity')(mag);
    force = inject.one('calculate steering')(entity.phys.b.velocity, mag);
    p2.vec2.scale(force, force, scale);
    return inject.one('apply force')(entity, force);
  });
});
