// Generated by CoffeeScript 1.7.1
define(['inject', 'p2'], function(inject, p2) {
  return inject.bind('separate', function(entity) {
    var averagerepulsion, force, istouched;
    averagerepulsion = [0, 0];
    inject.one('each by distance')(entity.phys.b.position, 25, function(d, e) {
      var diff;
      if (e === entity || (e.ai == null)) {
        return;
      }
      diff = [0, 0];
      p2.vec2.sub(diff, entity.phys.b.position, e.phys.b.position);
      p2.vec2.normalize(diff, diff);
      return p2.vec2.add(averagerepulsion, averagerepulsion, diff);
    });
    istouched = p2.vec2.len(averagerepulsion) !== 0;
    inject.one('abs stat')(entity, {
      istouched: istouched
    });
    if (!istouched) {
      return;
    }
    inject.one('scale to max velocity')(averagerepulsion);
    force = inject.one('calculate steering')(entity.phys.b.velocity, averagerepulsion);
    p2.vec2.scale(force, force, 2);
    return inject.one('apply force')(entity, force);
  });
});
