// Generated by CoffeeScript 1.7.1
define(['inject', 'p2'], function(inject, p2) {
  var maxvelocity;
  maxvelocity = 100;
  inject.bind('max velocity', maxvelocity);
  inject.bind('scale to max velocity', (function(_this) {
    return function(velocity) {
      p2.vec2.normalize(velocity, velocity);
      return p2.vec2.scale(velocity, velocity, maxvelocity);
    };
  })(this));
  return inject.bind('limit to max velocity', (function(_this) {
    return function(velocity) {
      var len;
      len = p2.vec2.len(velocity);
      len = Math.min(len, maxvelocity);
      p2.vec2.normalize(velocity, velocity);
      return p2.vec2.scale(velocity, velocity, len);
    };
  })(this));
});
