// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['inject', 'p2'], function(inject, p2) {
  var Unit;
  return Unit = (function() {
    function Unit(entity, n) {
      this.step = __bind(this.step, this);
      this.e = entity;
      this.n = n;
    }

    Unit.prototype.step = function() {
      var direction;
      direction = [random(2) - 1, random(2) - 1];
      p2.vec2.scale(direction, direction, 1000);
      inject.one('apply force')(this.e, direction);
      inject.one('separate')(this.e);
      inject.one('align')(this.e);
      return inject.one('cohere')(this.e);
    };

    return Unit;

  })();
});
